import * as XLSX from 'xlsx';
import { UniversalEvent } from '../types';

/**
 * Raw data rows representing the actual university timetable for group 26.М16-мо
 * Period: 7 сентября 2026 – 14 сентября 2026
 */
export const DEMO_SCHEDULE_ROWS = [
  ['26.М16-мо', 'Расписание занятий', '7 сентября 2026 — 14 сентября 2026'],
  ['Дата', 'Время', 'Название дисциплины', 'Места проведения', 'Преподаватели'],
  
  // Понедельник, 7 сентября 2026
  [
    'понедельник 7 сентября 2026',
    '11:10–12:40',
    'Дипломатия данных, лекция',
    'Смольный проезд, д. 1, лит. Б, ауд. 138',
    'проф. Сытник А. Н.',
  ],
  [
    '', // Data propagation test: empty date cell!
    '13:40–15:10',
    'Дипломатия данных, семинар',
    'Смольный проезд, д. 1, лит. Б, ауд. 138',
    'доц. Ковалевский Д. В.',
  ],
  [
    '',
    '15:20–16:50',
    'Электив. Основная траектория. Английский язык в сфере профессиональной коммуникации, практическое занятие Подгруппа 1',
    'Смольный проезд, д. 1, лит. Б, ауд. 204',
    'ст. преп. Морозова Е. С.',
  ],
  [
    '',
    '15:20–16:50',
    'Электив. Основная траектория. Английский язык в сфере профессиональной коммуникации, практическое занятие Подгруппа 2',
    'Смольный проезд, д. 1, лит. Б, ауд. 206',
    'преп. Васильев И. П.',
  ],
  [
    '',
    '15:20–16:50',
    'Электив. Основная траектория. Английский язык в сфере профессиональной коммуникации, практическое занятие Подгруппа 4',
    'Смольный проезд, д. 1, лит. Б, ауд. 210',
    'доц. Смирнова О. А.',
  ],
  // Exact duplicate to test deduplication
  [
    '',
    '15:20–16:50',
    'Электив. Основная траектория. Английский язык в сфере профессиональной коммуникации, практическое занятие Подгруппа 4',
    'Смольный проезд, д. 1, лит. Б, ауд. 210',
    'доц. Смирнова О. А.',
  ],

  // Вторник, 8 сентября 2026
  [
    'вторник 8 сентября 2026',
    '09:30–11:00',
    'Русский язык как иностранный, практическое занятие Подгруппа 1',
    'Смольный проезд, д. 1, лит. Б, ауд. 115',
    'доц. Иванова М. К.',
  ],
  [
    '',
    '09:30–11:00',
    'Русский язык как иностранный, практическое занятие Подгруппа 2',
    'Смольный проезд, д. 1, лит. Б, ауд. 118',
    'ст. преп. Петрова А. В.',
  ],
  [
    '',
    '11:10–12:40',
    'Актуальные проблемы теории международных отношений, лекция',
    'Смольный проезд, д. 1, лит. Б, ауд. 138',
    'проф. Новикова И. Н.',
  ],
  [
    '',
    '13:40–15:10',
    'Актуальные проблемы теории международных отношений, семинар',
    'Смольный проезд, д. 1, лит. Б, ауд. 138',
    'доц. Барышников Д. Н.',
  ],

  // Среда, 9 сентября 2026
  [
    'среда 9 сентября 2026',
    '11:10–12:40',
    'Цифровая трансформация мировой политики, лекция',
    'Университетская наб., д. 7-9, ауд. 32',
    'проф. Цветкова Н. А.',
  ],
  [
    '',
    '13:40–15:10',
    'Цифровая трансформация мировой политики, семинар',
    'Университетская наб., д. 7-9, ауд. 32',
    'доц. Ягья В. С.',
  ],

  // Четверг, 10 сентября 2026
  [
    'четверг 10 сентября 2026',
    '11:10–12:40',
    'Электив. Английский язык в сфере профессиональной коммуникации, практическое занятие Подгруппа 4',
    'Смольный проезд, д. 1, лит. Б, ауд. 210',
    'доц. Смирнова О. А.',
  ],
  [
    '',
    '11:10–12:40',
    'Электив. Английский язык в сфере профессиональной коммуникации, практическое занятие Подгруппа 2',
    'Смольный проезд, д. 1, лит. Б, ауд. 206',
    'преп. Васильев И. П.',
  ],
  [
    '',
    '13:40–15:10',
    'Анализ сетевых данных в международных исследованиях, лабораторная работа',
    'Смольный проезд, д. 1, лит. Б, компьютерный класс 215',
    'ст. преп. Кузнецов П. С.',
  ],

  // Пятница, 11 сентября 2026
  [
    'пятница 11 сентября 2026',
    '09:30–11:00',
    'Научно-исследовательский семинар, семинар',
    'Смольный проезд, д. 1, лит. Б, ауд. 138',
    'проф. Худолей К. К.',
  ],
  [
    '',
    '11:10–12:40',
    'Стратегические коммуникации в международных отношениях, лекция',
    'Смольный проезд, д. 1, лит. Б, ауд. 138',
    'доц. Маркушина Н. Ю.',
  ],
  // Суббота, 12 сентября 2026 - консультация
  [
    'суббота 12 сентября 2026',
    '11:10–12:40',
    'Консультация по курсовым проектам, консультация',
    'Смольный проезд, д. 1, лит. Б, ауд. 120',
    'доц. Барышников Д. Н.',
  ],
];

/**
 * Builds an actual binary XLSX file in memory as ArrayBuffer
 */
export function generateDemoExcelBuffer(): ArrayBuffer {
  const ws = XLSX.utils.aoa_to_sheet(DEMO_SCHEDULE_ROWS);
  // Style columns width
  ws['!cols'] = [
    { wch: 26 }, // Дата
    { wch: 14 }, // Время
    { wch: 60 }, // Название
    { wch: 40 }, // Место
    { wch: 30 }, // Преподаватели
  ];
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Расписание 26.М16-мо');
  const wbout = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  return wbout;
}

/**
 * Pre-seeded sample events for initial state if user wants demo data already active
 */
export function getInitialDemoEvents(): UniversalEvent[] {
  return [
    {
      id: 'demo-1',
      title: 'Дипломатия данных',
      date: '2026-09-07',
      startTime: '11:10',
      endTime: '12:40',
      eventType: 'pair',
      lessonType: 'lecture',
      lessonTypeName: 'Лекция',
      teacher: 'проф. Сытник А. Н.',
      location: '138',
      address: 'Смольный проезд, д. 1, лит. Б',
      subgroup: undefined,
      isElective: false,
      note: 'Взять ноутбук с установленным Python и pandas',
      reminder: '30min',
      source: 'imported',
      importedFrom: 'Расписание_26.М16-мо_07-14_сент.xlsx',
      createdAt: '2026-09-01T10:00:00.000Z',
      updatedAt: '2026-09-01T10:00:00.000Z',
    },
    {
      id: 'demo-2',
      title: 'Дипломатия данных',
      date: '2026-09-07',
      startTime: '13:40',
      endTime: '15:10',
      eventType: 'pair',
      lessonType: 'seminar',
      lessonTypeName: 'Семинар',
      teacher: 'доц. Ковалевский Д. В.',
      location: '138',
      address: 'Смольный проезд, д. 1, лит. Б',
      subgroup: undefined,
      isElective: false,
      note: 'Прочитать статью Энтмана к семинару',
      reminder: '10min',
      source: 'imported',
      importedFrom: 'Расписание_26.М16-мо_07-14_сент.xlsx',
      createdAt: '2026-09-01T10:00:00.000Z',
      updatedAt: '2026-09-01T10:00:00.000Z',
    },
    {
      id: 'demo-3',
      title: 'Английский язык в сфере проф. коммуникации',
      date: '2026-09-07',
      startTime: '15:20',
      endTime: '16:50',
      eventType: 'pair',
      lessonType: 'practice',
      lessonTypeName: 'Практическое занятие',
      teacher: 'доц. Смирнова О. А.',
      location: '210',
      address: 'Смольный проезд, д. 1, лит. Б',
      subgroup: '4',
      isElective: true,
      note: 'Unit 1: Diplomatic Discourse, упражнения 4-8',
      reminder: '30min',
      source: 'imported',
      importedFrom: 'Расписание_26.М16-мо_07-14_сент.xlsx',
      createdAt: '2026-09-01T10:00:00.000Z',
      updatedAt: '2026-09-01T10:00:00.000Z',
    },
    {
      id: 'demo-4',
      title: 'Актуальные проблемы теории МО',
      date: '2026-09-08',
      startTime: '11:10',
      endTime: '12:40',
      eventType: 'pair',
      lessonType: 'lecture',
      lessonTypeName: 'Лекция',
      teacher: 'проф. Новикова И. Н.',
      location: '138',
      address: 'Смольный проезд, д. 1, лит. Б',
      subgroup: undefined,
      isElective: false,
      reminder: 'none',
      source: 'imported',
      importedFrom: 'Расписание_26.М16-мо_07-14_сент.xlsx',
      createdAt: '2026-09-01T10:00:00.000Z',
      updatedAt: '2026-09-01T10:00:00.000Z',
    },
    {
      id: 'demo-5',
      title: 'Актуальные проблемы теории МО',
      date: '2026-09-08',
      startTime: '13:40',
      endTime: '15:10',
      eventType: 'pair',
      lessonType: 'seminar',
      lessonTypeName: 'Семинар',
      teacher: 'доц. Барышников Д. Н.',
      location: '138',
      address: 'Смольный проезд, д. 1, лит. Б',
      subgroup: undefined,
      isElective: false,
      note: 'Подготовить тезисы по структурному реализму',
      reminder: '1hour',
      source: 'imported',
      importedFrom: 'Расписание_26.М16-мо_07-14_сент.xlsx',
      createdAt: '2026-09-01T10:00:00.000Z',
      updatedAt: '2026-09-01T10:00:00.000Z',
    },
    {
      id: 'demo-6',
      title: 'Сдать тему курсовой работы',
      date: '2026-09-08',
      startTime: '17:00',
      endTime: '17:30',
      eventType: 'deadline',
      lessonType: 'other',
      lessonTypeName: 'Дедлайн',
      location: 'Деканат',
      note: 'Отправить заявление научному руководителю на согласование',
      reminder: '1day',
      source: 'manual',
      createdAt: '2026-09-02T12:00:00.000Z',
      updatedAt: '2026-09-02T12:00:00.000Z',
    },
    {
      id: 'demo-7',
      title: 'Цифровая трансформация мировой политики',
      date: '2026-09-09',
      startTime: '11:10',
      endTime: '12:40',
      eventType: 'pair',
      lessonType: 'lecture',
      lessonTypeName: 'Лекция',
      teacher: 'проф. Цветкова Н. А.',
      location: '32',
      address: 'Университетская наб., д. 7-9',
      subgroup: undefined,
      isElective: false,
      reminder: 'none',
      source: 'imported',
      importedFrom: 'Расписание_26.М16-мо_07-14_сент.xlsx',
      createdAt: '2026-09-01T10:00:00.000Z',
      updatedAt: '2026-09-01T10:00:00.000Z',
    },
    {
      id: 'demo-8',
      title: 'Цифровая трансформация мировой политики',
      date: '2026-09-09',
      startTime: '13:40',
      endTime: '15:10',
      eventType: 'pair',
      lessonType: 'seminar',
      lessonTypeName: 'Семинар',
      teacher: 'доц. Ягья В. С.',
      location: '32',
      address: 'Университетская наб., д. 7-9',
      subgroup: undefined,
      isElective: false,
      note: 'Доклад: влияние ИИ на международные переговоры',
      reminder: '30min',
      source: 'imported',
      importedFrom: 'Расписание_26.М16-мо_07-14_сент.xlsx',
      createdAt: '2026-09-01T10:00:00.000Z',
      updatedAt: '2026-09-01T10:00:00.000Z',
    },
    {
      id: 'demo-9',
      title: 'Купить учебники в книжном отделе',
      date: '2026-09-09',
      startTime: '15:40',
      endTime: '16:30',
      eventType: 'personal',
      lessonType: 'other',
      lessonTypeName: 'Личное событие',
      location: 'Книжная лавка',
      note: 'Хрестоматия по международному праву',
      reminder: '10min',
      source: 'manual',
      createdAt: '2026-09-02T14:00:00.000Z',
      updatedAt: '2026-09-02T14:00:00.000Z',
    },
    {
      id: 'demo-10',
      title: 'Английский язык в сфере проф. коммуникации',
      date: '2026-09-10',
      startTime: '11:10',
      endTime: '12:40',
      eventType: 'pair',
      lessonType: 'practice',
      lessonTypeName: 'Практическое занятие',
      teacher: 'доц. Смирнова О. А.',
      location: '210',
      address: 'Смольный проезд, д. 1, лит. Б',
      subgroup: '4',
      isElective: true,
      note: 'Подготовить case study к обсуждению',
      reminder: '30min',
      source: 'imported',
      importedFrom: 'Расписание_26.М16-мо_07-14_сент.xlsx',
      createdAt: '2026-09-01T10:00:00.000Z',
      updatedAt: '2026-09-01T10:00:00.000Z',
    },
    {
      id: 'demo-11',
      title: 'Анализ сетевых данных в межд. исследованиях',
      date: '2026-09-10',
      startTime: '13:40',
      endTime: '15:10',
      eventType: 'pair',
      lessonType: 'lab',
      lessonTypeName: 'Лабораторная работа',
      teacher: 'ст. преп. Кузнецов П. С.',
      location: '215',
      address: 'Смольный проезд, д. 1, лит. Б',
      subgroup: undefined,
      isElective: false,
      note: 'Лабораторная №1 по Gephi',
      reminder: '10min',
      source: 'imported',
      importedFrom: 'Расписание_26.М16-мо_07-14_сент.xlsx',
      createdAt: '2026-09-01T10:00:00.000Z',
      updatedAt: '2026-09-01T10:00:00.000Z',
    },
    {
      id: 'demo-12',
      title: 'Научно-исследовательский семинар',
      date: '2026-09-11',
      startTime: '09:30',
      endTime: '11:00',
      eventType: 'pair',
      lessonType: 'seminar',
      lessonTypeName: 'Семинар',
      teacher: 'проф. Худолей К. К.',
      location: '138',
      address: 'Смольный проезд, д. 1, лит. Б',
      subgroup: undefined,
      isElective: false,
      reminder: 'none',
      source: 'imported',
      importedFrom: 'Расписание_26.М16-мо_07-14_сент.xlsx',
      createdAt: '2026-09-01T10:00:00.000Z',
      updatedAt: '2026-09-01T10:00:00.000Z',
    },
    {
      id: 'demo-13',
      title: 'Стратегические коммуникации в МО',
      date: '2026-09-11',
      startTime: '11:10',
      endTime: '12:40',
      eventType: 'pair',
      lessonType: 'lecture',
      lessonTypeName: 'Лекция',
      teacher: 'доц. Маркушина Н. Ю.',
      location: '138',
      address: 'Смольный проезд, д. 1, лит. Б',
      subgroup: undefined,
      isElective: false,
      reminder: '30min',
      source: 'imported',
      importedFrom: 'Расписание_26.М16-мо_07-14_сент.xlsx',
      createdAt: '2026-09-01T10:00:00.000Z',
      updatedAt: '2026-09-01T10:00:00.000Z',
    },
  ];
}
